hydra:
    run:
        dir: ./results/${env_name}/${hydra.job.name}/${now:%Y-%m-%d_%H%M%S}_${seed}

# Env config
seed: 42
env_name: rastrigin
episode_length: 1

# MOME parameters
pareto_front_max_length: 50
num_objective_functions: 2
reference_point: [-150, -150]

# Initialisation parameters
batch_size: 256 
num_evaluations: 100000
num_centroids: 128
num_init_cvt_samples: 20000

# Rastrigin parameters
num_param_dimensions: 100
num_descriptor_dimensions: 2
minval: -2 
maxval: 4 
lag: 2.2 
base_lag: 0 

# Emitter parameters
proportion_to_mutate: 0.6 
eta: 1 
proportion_var_to_change: 0.5 
crossover_percentage: 1. 

# Logging parameters
metrics_log_period: 10
plot_repertoire_period: 20
checkpoint_period: 30
save_checkpoint_visualisations: False
save_final_visualisations: False
num_save_visualisations: 5
