hydra:
    run:
        dir: ./results/${env_name}/${algo_name}/${now:%Y-%m-%d_%H%M%S}_${seed}

# Env config
seed: 42
env_name: walker2d_multi
algo_name: nsga2
fixed_init_state: True
episode_length: 1000

# MO parameters
num_objective_functions: 2

# MOME parameters (for creating passive archive)
pareto_front_max_length: 50
num_init_cvt_samples: 50000 
num_centroids: 128 

# Initialisation parameters
population_size: 6400 #=PF size x num centroids
batch_size: 256
num_evaluations: 1024000

# Brax parameters
num_descriptor_dimensions: 2
policy_hidden_layer_sizes: [64, 64]

# Min and max val of BDs
minval: 0. 
maxval: 1.

# Emitter parameters
iso_sigma: 0.005 
line_sigma: 0.05 
proportion_to_mutate: 0.6 # don't actually use this as purely crossover
eta: 1 
crossover_percentage: 1. 

# Logging parameters
metrics_log_period: 50
plot_repertoire_period: 400
checkpoint_period: 500
save_checkpoint_visualisations: False
save_final_visualisations: True
num_save_visualisations: 5


